### ISSUE TITLE
4.3.1 and up Break Rest+

### ISSUE THREAD

**Issue by DeltaEchoFour** [dgreif/homebridge-hatch-baby-rest#126] opened 2024-03-11 03:28 UTC
When using 4.3.0, my Rest+ works great. In 4.3.1 and 4.3.2, it's not recognized.

Using 4.3.0, I see this:

`[3/9/2024, 11:07:07 PM] [HatchBabyRest] Unsupported Product Found: grow
[3/9/2024, 11:07:07 PM] [HatchBabyRest] Unsupported Product Found: answeredReader
[3/9/2024, 11:07:07 PM] [HatchBabyRest] Configuring Hatch Devices:
[3/9/2024, 11:07:07 PM] [HatchBabyRest]   Rest+: 1
[3/9/2024, 11:07:07 PM] [HatchBabyRest] Adding new Hatch Rest+ - Michael’s Room`

Using 4.3.1/4.3.2, I see this:

`[3/10/2024, 11:26:41 PM] [HatchBabyRest] Unsupported Product Found: answeredReader. Set `"debug": true` in your config to see more device details.
[3/10/2024, 11:26:41 PM] [HatchBabyRest] Configuring Hatch Devices:
[3/10/2024, 11:26:41 PM] [HatchBabyRest]   No supported devices found
[3/10/2024, 11:26:41 PM] [HatchBabyRest] Removing stale cached accessory 0c5088ba-c5cb-4be1-b224-62b37d53afe5 Michael’s Room`

This is reproducible quite easily in my environment.

Thanks for looking into this!

**Comment by stevenharman** [comment] 2024-03-29 02:42
I'm seeing the same thing with my Hatch Mini.

```
[HatchBabyRest] Unsupported Product Found: answeredReader
[HatchBabyRest] Configuring Hatch Devices:
[HatchBabyRest]   No supported devices found
```

**Comment by dgreif** [comment] 2024-03-29 21:01
This is a duplicate of #125

**Closed by dgreif** 2024-03-29 21:01 UTC
