### ISSUE TITLE
config option to only include the BaseAcessory (master on/off switch)

### ISSUE THREAD

**Issue by steveredden** [dgreif/homebridge-hatch-baby-rest#58] opened 2021-08-23 02:04 UTC
Can you add a checkbox for not deploying the additional accessories?  I've only found use of the master switch so far.

`config.schema.json`
```
"includeExtraAccessories": {
  "title": "Include Extra Accessories",
  "type": "boolean",
  "description": "Include Soundtrack Fan, Volume, and Light Accessories (where applicable)",
  "placeholder": "zInclude Extra Accessories",
  "default": "true",
  "oneOf": [
    { "title": "Yes", "enum": ["true"] },
    { "title": "No", "enum": ["false"] }
  ],
  "required": false
},
```

![image](https://user-images.githubusercontent.com/35814432/130380150-c97026d2-d654-480f-bcfb-dcf3c9ae0a12.png)

was planning a PR but wasn't sure where to implement in `platform.ts` - maybe lines 105:115?

Or maybe you could help me customize out the extra accessories?

**Comment by dgreif** [comment] 2021-08-25 03:46
This is a duplicate of #53.  I don't see much value in adding extra configuration just to remove accessories in this case.

**Closed by dgreif** 2021-08-25 03:46 UTC

**Comment by steveredden** [comment] 2021-08-25 11:57
How about at least polling for the master’s state and turn off the light/fan/volume? It’s “odd” to see these constantly “on.”

that’s the main reason I find them annoying.

Or just implement the twice-asked request :P
